
name: Workflow on merged request

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Directory
      run: pwd
    - name: Directory 1
      run: python --version
    - name: Run Unit Test
      run: python UnitTest.py 
    - name: Build python artifacts
      run: tar -cf app.tar.gz *.py *.service *.json
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     # build artifact
    - name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ami.pkr.hcl

