name: Workflow on merged requests Full

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Directory
      run: pwd
    - name: Directory 1
      run: python --version
    - name: Run Unit Test
      run: python UnitTest.py 
    - name: Build python artifacts
      run: tar -cf app.tar.gz *.py *.service *.json
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    - name: download packer
      run: curl -LO https://raw.github.com/robertpeteuil/packer-installer/master/packer-install.sh
    - name: download packer permission
      run: chmod +x packer-install.sh
    - name: download packer permission
      run: ./packer-install.sh
    - name: validate packer
      run: packer validate ami.pkr.hcl    
    - name: build packer
      run: packer build ami.pkr.hcl | tee ami_id.txt
    - name: Configure AWS Credentials for demo
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_Demo }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_Demo }}
          aws-region: us-east-1
    - name: check 1
      run: |
          cat ami_id.txt
    - name: check
      run: |
          s1=$(tail -2 ami_id.txt | cut -c 12-32)
          echo $s1
    - name: AWS new launch template version
      run: |
          s1=$(tail -2 ami_id.txt | cut -c 12-32)
          echo $s1
          aws ec2 create-launch-template-version --launch-template-name assignment8-launch-template --version-description WebVersion --source-version 1 --launch-template-data ImageId=$s1
    - name: AWS Update ASG
      run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name assignment8-asg --launch-template LaunchTemplateName='assignment8-launch-template',Version='$Latest'
    - name: AWS instance refresh
      run: |      
          aws autoscaling start-instance-refresh --auto-scaling-group-name assignment8-asg
      
      
    
      
    
      
