name: Python application

on: 
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Print directory
      run: pwd
    - name: Run python Test
      run: python D:\a\webapp\webapp\Assignment_2\test.py
        
